INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES (1, 'I Started A joke', DEFAULT, DEFAULT, 'The morning of June 27th was clear and sunny, with the fresh warmth of a full-summer day; the flowers were blossoming profusely and the grass was richly green.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(2, 'Me and Mr. Jones', DEFAULT, DEFAULT, 'During the whole of a dull, dark, and soundless day in the autumn of the year, when the clouds hung oppressively low in the heavens, I had been passing alone, on horseback, through a singularly dreary tract of country.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(3, 'The Gift', DEFAULT, DEFAULT, 'ONE DOLLAR AND EIGHTY-SEVEN CENTS. That was all.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(4, 'Old Man at the Bridge', DEFAULT, DEFAULT, 'An old man sits at the side of a country road during the Spanish civil war. Everyone is fleeing the area, and although he has already traveled 12 kilometers, he is too exhausted and distracted to continue');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(5, 'Honey, I pranked the kids', DEFAULT, DEFAULT, 'The night is thick and heavy with clouds when I paint the front of The House yellow. I paint quickly and quietly.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(1, 'Just Ask for Mercy', DEFAULT, DEFAULT, 'Something is eating at Hostas.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(2, '10 Days', DEFAULT, DEFAULT, 'My 10 day-diet started out with me banging my head furiosly onto the fridge so I associate pain with it');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(3, 'Unseen', DEFAULT, DEFAULT, 'Sirens woke me and brothers up early in the morning.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(4, 'Honey, I lost the kids', DEFAULT, DEFAULT, 'Today, I decided to bring my kids to see a local play.');
INSERT INTO stories (creator_id, title, active_status, created_at, intro_text) VALUES(5, 'Kids, I lost Honey', DEFAULT, DEFAULT, 'I just never learn...');

