DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  password VARCHAR(255)
);

DROP TABLE IF EXISTS stories CASCADE;
CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) DEFAULT "untitled",
  active_status BOOLEAN NOT NULL DEFAULT TRUE,
  created_at NOT NULL DEFAULT Now(),
  intro_text text NOT NULL,

);

DROP TABLE IF EXISTS contributions CASCADE;
CREATE TABLE contributions (
  id SERIAL PRIMARY KEY NOT NULL,
  contributor_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  story_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  contribution text NOT NULL,
  created_at NOT NULL DEFAULT Now(),
  creator_accepted BOOLEAN NOT NULL DEFAULT FALSE,

);

DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE VOTES (
  id SERIAL PRIMARY KEY NOT NULL,
  contributor_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  contribution_id INTEGER REFERENCES contributions(id) ON DELETE CASCADE
);
